# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18' # [Required] Define the Elixir version
        otp-version: '27'      # [Required] Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v3
      env:
        base-key: '27-1.18'
      with:
        path: deps
        key: ${{ env.base-key }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ env.base-key }}-mix
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
